# --- 字体与显示 ---
font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- 窗口样式 ---
window_padding_width 10
background_opacity 0.92
background_tint    0.97
# 让背景与 Breeze Dark 融合
background_blur    1

# --- 窗口边框 (Breeze 蓝) ---
window_border_width  1.0pt
active_border_color  #3daee9
inactive_border_color #31363b
draw_minimal_borders yes

# --- 标签栏 ---
tab_bar_style        powerline
active_tab_foreground   #eff0f1
active_tab_background   #3daee9
inactive_tab_foreground #bdc3c7
inactive_tab_background #31363b

# --- 系统集成 ---
term xterm-256color
shell_integration enabled
allow_hyperlinks yes
editor nvim
confirm_os_window_close 0

# 引入我们修改后的主题文件
include theme.conf
